edition = "2024"
style_edition = "2024"
unstable_features = true
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
tab_spaces = 3
hard_tabs = false
fn_params_layout = "Compressed"
# fn_params_layout = "Compressed"
fn_single_line = true
max_width = 150
fn_call_width = 120
attr_fn_like_width = 120
chain_width = 60
single_line_if_else_max_width = 120
single_line_let_else_max_width = 120
comment_width = 120
inline_attribute_width = 120
format_strings = true
overflow_delimited_expr = true
struct_field_align_threshold = 30
empty_item_single_line = true
imports_indent = "Visual"
indent_style = "Visual"
match_arm_leading_pipes = "Always"
imports_granularity = "Crate"
reorder_impl_items = true
reorder_imports = false
group_imports = "StdExternalCrate"
short_array_element_width_threshold = 60
# use_small_heuristics = "Max"
